version: '3.0'
services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - database.env
    volumes:
      - database:/var/lib/mysql:Z
      - ./initial-database.sql:/docker-entrypoint-initdb.d/01-initialize.sql:ro
  
  app:
    build: .
    restart: unless-stopped
    environment:
      - APP_DATABASE_HOST=db
    env_file:
      - database.env
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  database: