name: Build and Publish Matchmaking Docker Image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-matchmaking:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for matchmaking service
        id: meta_matchmaking
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-matchmaking

      - name: Build and push matchmaking Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./matchmaking
          push: true
          tags: ${{ steps.meta_matchmaking.outputs.tags }}
          labels: ${{ steps.meta_matchmaking.outputs.labels }}
