name: Deployment webhook (Matchmaking & Game)

# Only trigger when the specified workflows have succeeded
on:
  workflow_run:
    workflows: ["build_image_game", "build_image_matchmaking"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Trigger deployment webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"text": "All checks passed and deployment is starting."}' http://webhooks.ivo-zilkenat.de/hooks/distributed-systems-io-deploy
